run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - stylecheck
    - gosec
    - gocritic

linters-settings:
  gofmt:
    simplify: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentFormatting

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
